### ISSUE TITLE
idk what this is...

### ISSUE THREAD

**Issue by PartOfCheese** [fnar/minecraft-roguelike#67]
[13:35:52] [Server thread/INFO] [roguelike]: Trying to spawn dungeon at chunkX 51 and chunkZ 0...
[13:35:52] [Server thread/INFO] [roguelike]: Trying to spawn dungeon with id fnar:dungeon_cave at {"x": 967, "y": 0, "z": -54}...
[13:36:04] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:performTaskSafely:137]: com.github.fnar.util.ReportThisIssueException: Please report this issue at https://github.com/fnar/minecraft-roguelike/issues: 
[13:36:04] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:performTaskSafely:137]: 	at greymerk.roguelike.dungeon.Dungeon.performTaskSafely(Dungeon.java:137)
[13:36:04] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:performTaskSafely:137]: 	at greymerk.roguelike.dungeon.Dungeon.lambda$generate$1(Dungeon.java:124)
[13:36:04] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:performTaskSafely:137]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)

**Comment by fnar** [comment]
Thanks for this report, @PartOfCheese. Do you happen to have more of the stack trace? A few more lines could go a long way (and many more even further).
